#!/bin/sh

echo "Stahsing local changes."
git stash

echo "Fetching latest commit from the svn repository."
git svn fetch
git svn rebase

echo "Sending all local commits to the svn repository."
git svn dcommit

echo "Reapplying local change to source from the stash."
git stash pop

